### ISSUE TITLE
CMake Unknown arguments specified

### ISSUE THREAD

**Issue by Harm10** [xavery/dcue#21]
Hi! I am trying to build dcue on Windows using CMake version 3.29.2
When I do so I get this error:

CMake Error at CMakeLists.txt:8 (if):
  if given arguments:

    "STREQUAL" "Debug"

  Unknown arguments specified
  
  Do I need to use an older version of CMake?

**Comment by soapbreaks** [comment]
i've gotten this exact problem when debugging too
https://imgur.com/a/VQHfGUu

**Comment by lighterowl** [comment]
This should have been fixed by #15 , have you tried the tip of `develop`?

**Comment by Harm10** [comment]
Develop does not throw this error.
But then I get an error on line 30 for spdlog: does not contain a CMakeLists.txt file.
Which is correct as the whole folder spdlog is empty.

I might have added that I use CMake GUI.

**Comment by lighterowl** [comment]
You haven't cloned the submodules. To quote the `README` on compiling :

> Also remember to include submodules in your clone : the easiest way to do that is to add `--recurse-submodules` to the git clone commandline.

**Comment by Harm10** [comment]
I see this instruction. As I always do I just download the zip from GitHub and this apparently does not include the required modules. I also do not see an option for that to include them. So I think a warning should be in order with that part of the README: to NOT download the zip?

If I try to clone the repo in VSCode the normal way it also fails to include these other repo's. It detects them (that preference is switched on in my settings) but does not clone them right away. I searched some settings and found that you need to execute Clone (Recursive) in VSCode. So I managed to clone the develop branch.
I never work with CLI for cloning. I guess I am not the only one............... :-)

So now the build gives these errors:

CMake Error in CMakeLists.txt:
  OUTPUT containing a "#" is not allowed.


CMake Error in CMakeLists.txt:
  OUTPUT containing a "#" is not allowed.


CMake Error in spdlog/CMakeLists.txt:
  OUTPUT containing a "#" is not allowed.

I changed the CMAKE_INSTALL_PREFIX to point to the desired folder (which does not exist yet).
But I do not know what to select in the SPDLOG settings (it is a long list). Do I need to select some? It is not mentioned in the README.

I think it has to do with the Build location I provide: F:/#Audio/cuesheet/dcue-build
That contains an # character. Is this a bug in CMake?

**Comment by lighterowl** [comment]
> But I do not know what to select in the SPDLOG settings (it is a long list). Do I need to select some? It is not mentioned in the README.

You don't need to change any of those settings.

> 
> I think it has to do with the Build location I provide: F:/#Audio/cuesheet/dcue-build That contains an # character. Is this a bug in CMake?

It looks like it's a Windows-only quirk in CMake : https://gitlab.kitware.com/cmake/cmake/-/issues/25604

Also, keep in mind that this project doesn't really use `install`, as the release packages consist only of the main executable that's pulled straight from the build directory, as seen [here](https://github.com/xavery/dcue/blob/develop/.github/win_official.bat) and [here](https://github.com/xavery/dcue/blob/develop/.github/lnx_official.sh). So I have no idea what you're going to end up with in your `CMAKE_INSTALL_PREFIX`.

**Comment by Harm10** [comment]
So I ran the CMake build in another folder (without # in the name). The generation went fine.
And now what? As you expected there is no exec in the build folder.
The GUI has an option "Open project" and then it picks dcue.sln and gives me a pop-up to select the application to open it with. But that list is empty.
So how to continue to get a working dcue?
I do use VSCode but do not have Visual Studio installed. Should I do that?

**Comment by lighterowl** [comment]
Sorry, I don't use Windows for development. Please look for some other resources for help.

**Comment by Harm10** [comment]
@xavery Any suggestions where I could look?
