### ISSUE TITLE
Missing Artist Elements (e.g. "Feat.")

### ISSUE THREAD

**Issue by mattbisme** [xavery/dcue#5]
Just started using DCUE; pretty cool! However, I noticed an issue when there are multiple artists for a single track. For example, when generating CUEs for [this album](https://www.discogs.com/Various-Hardcore-Underground-5/release/3151795), if the artist is "`CLSM` Feat. `Lisa Abbott`" (where CLSM and Lisa Abbott are linked artists), DCUE will drop the "Feat." resulting in "CLSM Lisa Abbott" as the entered artist. Similarly, it will also drop "&" unless it's a part of the linked Artist name itself. DCUE also fails to include a space when listing artists with commas:
"Artist1,Artist2"

It seems this album has a lot of little things like this, so, I'll have a lot of cleanup to do… but, it's still a lot less work than having to generate my own CUE file!

**Comment by lighterowl** [comment]
Thanks for the report, this is now fixed by properly using the "join string" in the artist specification found in the release JSON. The spaces around the string are always added, and if the "join string" is not specified, it is replaced by a comma.

In a nutshell, this means that, for example, `Hixxy Euphony Donna Marie` is now properly specified as `Hixxy & Euphony Feat. Donna Marie` in the CUE files.

Let me know if it all this sounds okay to you and I'll make a new release, as this bug seems significant enough to warrant one.

**Comment by mattbisme** [comment]
Taken at face value, that sounds exactly correct. I have some albums that I can test it on, including the one that I mentioned, once there is a new release. Thanks!

**Comment by mattbisme** [comment]
I built from source and tried it on the [same album](https://www.discogs.com/Various-Hardcore-Underground-5/release/3151795). Much better results! However, there are some scenarios where the comma is placed after a space (perhaps, instead of replacing it?). For example, CD1, Track 3 becomes `Al Storm , Technikore & JTS`. Screenshot attached for the full results. 

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/5126680/116005841-bdc01a80-a5d6-11eb-8e1b-e6f05e82e766.png">

**Comment by lighterowl** [comment]
Alright, f744b660a01decf3ed967a9e731e622ad1dd2466 fixes this : there will be no extra space before the join string if it is a single comma. I don't think there are any other characters which would require such behaviour (the only single-character one used in the current examples is `&` which would look weird without spaces on both sides), unless you can think of some?

**Comment by lighterowl** [comment]
@mattbisme ping

**Comment by mattbisme** [comment]
Everything looks good so far! I can't think of anything other than commas that would only have one space. Most other delimiters aren't really seen in this context (colons, semi-colons). Not sure if a `/` ever comes up on Discogs; I could see that happening. You'd maybe want no spaces in that case. But, even that wouldn't look terrible with spaces on both sides.

**Comment by lighterowl** [comment]
Alright, the freshly released [version 1.4](https://github.com/xavery/dcue/releases/tag/1.4) now includes the changes mentioned here, in case you need an official build.
