### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Potatof** [xavery/dcue#8]
I had an "Access Denied" when launching the Windows binary in the user folder, did I miss something?
... and at the end windows declares that dcue.exe contains Program:Win32/Uwasson.A!ml

**Comment by lighterowl** [comment]
The release binaries are built straight from the sources in the repository which can be verified by checking the SHA256 sums in the build log. There's no malware in there. Unfortunately, 3 antivirus solutions disagree, [according to VirusTotal](https://www.virustotal.com/gui/file/3f7dde5c8ef175a45ff91c7d34e91471226941a27ec81d3e328cfc38495e207c/detection).

I don't know what else there is that I can say.
